# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SevenSeg_XDC.xdc
set_property DONT_TOUCH TRUE [get_cells Seven_Seg_Mult -quiet] -quiet

# XDC: new/Motor_XDC.xdc
set_property DONT_TOUCH TRUE [get_cells pwm -quiet] -quiet
